### PR TITLE
specifying `_pd_read_kwds` for unemployment and zipcodes datasets

### PR DESCRIPTION
**Pull request by yy**
Addressing issue #16 

This commit specifies the separator (tab) for the `unemployment` data and `dtype` for `zip_code` variable in `zipcodes` dataset.

### CODE REVIEW

**Comment by jakevdp** [comment]
Thanks!

Looking at the unemployment data, that should have worked automatically because it is a tsv file. Turns out there was a bug in tsv handling that I just pushed a fix & test for: #18 So you can remove the ``Unemployment`` class; it should work without it now.

Regarding zipcodes: is there a reason to prefer categories rather than strings in this case?

**Comment by yy** [comment]
Great! I don't have a strong opinion on categorical vs. string. I just think that ZIP codes are categories in nature (maybe because I'm using it as a categorical variable in regression etc.). But I can see that ZIP codes are hierarchically organized and thus also makes sense to have it as a string.

**Comment by jakevdp** [comment]
I think we should switch to strings then... I think categories make sense when you have many instances within each category. Here there is only a single instance of each category, and so strings are slightly more efficient.

**Comment by jakevdp** [comment]
Looks great! Could you also add a test of the zipcode data type?

**Comment by yy** [comment]
Merged master and added a minor fix to `test_unemployment_tsv()`.

**Comment by jakevdp** [comment]
Thanks!

**Pull request merged**
