### PR TITLE
ENH: Change to CDN for base url

### LINKED ISSUE #41: Consider using CDN for the base url
In [vega/vega-datasets](https://github.com/vega/vega-datasets) they recommend using a CDN with a fixed version to access the URLs for a dataset such as 

https://cdn.jsdelivr.net/npm/vega-datasets@1.31/data/cars.json

instead of 

https://vega.github.io/vega-datasets/data/cars.json

I was wondering if we should make this change as well?

I think modifications would take place here:

https://github.com/altair-viz/vega_datasets/blob/70d6829f9a158c7e07f56291ce02c9bcd019acdd/vega_datasets/core.py#L94

but it would be cool if it could grab the correct version number from 

https://github.com/altair-viz/vega_datasets/blob/70d6829f9a158c7e07f56291ce02c9bcd019acdd/vega_datasets/__init__.py#L9

Anyways, just an idea moving forward to try to make things more stable

### PR DESCRIPTION
**Pull request by eitanlees**
resolves #41

### CODE REVIEW

**Comment by eitanlees** [comment]
```bash
vega_datasets/__init__.py:5:1: E402 module level import not at top of file
```


So the build is failing `flake8` because I moved `SOURCE_TAG` to the top of the `__init__.py` file. The reason I did this is so it can be referenced in `core.py`

What do you recomend? 

We could change the test to ignore `E402`, or do something else to access the `SOURCE_TAG`. Maybe even more it into `core.py`?

**Comment by eitanlees** [comment]
I went ahead and moved `SOURCE_TAG` into `core.py`. 

I also modified `generate_datasets_json.py` such that it updates the correct file. 

I think this should be working as expected now.

**Comment by jakevdp** [comment]
Looks good! To populate the new URLs within the package, run ``python tools/generate_datasets_json.py``

**Comment by eitanlees** [comment]
yes, I checked that it worked locally

**Comment by jakevdp** [comment]
Thanks!

**Pull request merged**
